# Generated by Django 5.1.1 on 2024-09-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_customuser_address_alter_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_profile.webp', upload_to='profile_images/'),
        ),
    ]
