# Generated by Django 5.1.1 on 2024-09-11 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
        ('ticket', '0003_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.ticket'),
        ),
    ]
