# Generated by Django 5.1.1 on 2024-09-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_history_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Histories'},
        ),
    ]
