# Generated by Django 5.1.1 on 2024-09-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
